name: Docs Deployment
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Storybook
        run: yarn build-storybook
      - name: Prepare
        run: |
          mv ./storybook-static ./packages/docs/build/storybook
          echo 'rct.lukasbach.com' >> ./packages/docs/build/CNAME
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/docs/build
          CLEAN: true
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: lukasbachbot
          GIT_CONFIG_EMAIL: bot@noreply.lukasbach.com
