name: Verify
on: push

jobs:
  react-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [ 16, 17, 18 ]
    name: React ${{ matrix.react }} Build
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: Dependencies
        run: yarn
      - name: Custom React version
        run: |
          echo "enableImmutableInstalls: false" > ./.yarnrc.yml
          yarn add react@${{ matrix.react }} -D
          cd packages/core
          yarn add react@${{ matrix.react }} -D
          cd ../..
          cat ./.yarnrc.yml
          yarn
      - name: Build
        run: yarn build

  verify:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Storybook
        run: yarn build-storybook
